### ISSUE TITLE
Cannot find module 'rrweb-snapshot' or its corresponding type declarations

### ISSUE THREAD

**Issue by loremaps** [PostHog/posthog-js#252]
Hi,

I get the following error when trying to upgrade to a later version than `v1.9.7`

```
Error: node_modules/posthog-js/dist/module.d.ts:4:50 - error TS2307: Cannot find module 'rrweb-snapshot' or its corresponding type declarations.

4 import { MaskInputOptions, SlimDOMOptions } from 'rrweb-snapshot'
```

this is for an Angular 12 project

It looks related to this:

https://github.com/PostHog/posthog-js/blob/923e82d498eb6a80d4f185c368b120ff9587ee95/src/module.d.ts#L4

Should [rrweb-snapshot](https://github.com/rrweb-io/rrweb-snapshot) be added to the dependencies?

FYI it works fine if I install `rrweb-snapshot` separately.

**Comment by Twixes** [comment]
Does this still happen on the latest version?

**Comment by loremaps** [comment]
Yes, it does for version `v1.12.1`

**Comment by novocaine** [comment]
👋  We are encountering the same issue while validating type definitions using `tsc`. We aren't currently using `rrweb` or `sentry` (which types are also being loaded from).

We would prefer not to force our users to install those dependencies which we are not using. Would you consider a different approach to re-exporting the types of other libraries in your interface? Perhaps we can duplicate the types in posthog's `module.d.ts`?

**Comment by Twixes** [comment]
Hey! We released `posthog-js` 1.12.3 which should fix this for now by adding `rrweb-snapshot` to dev-only dependencies. Could you try it out and see if that works better for you?

**Comment by loremaps** [comment]
Hi @Twixes, the issue is still there for me. I created a [small repo to reproduce it](https://github.com/loremaps/posthog-repro) for your convenience.

So far the only solution that works for me is to install `rrweb-snapshot` and `@sentry/types` as devDependencies.

**Comment by novocaine** [comment]
> Hi @Twixes, the issue is still there for me. I created a [small repo to reproduce it](https://github.com/loremaps/posthog-repro) for your convenience.
> 
> So far the only solution that works for me is to install `rrweb-snapshot` and `@sentry/types` as devDependencies.

We have the same problem. Adding the dependencies as dev only dependencies won't help, npm doesn't install the devDependencies of a project's transitive dependencies.

**Comment by Twixes** [comment]
@loremaps A reproducible example is fantastic, thank you!

@novocaine You are of course correct, `devDependencies` is the wrong lead here. Hence I created #265 that fixes the problem definitively.

**Comment by loremaps** [comment]
> I've just added posthog to my Angular 18 project and I'm having this exact issue. What can I do to resolve it?

Can you try adding `"skipLibCheck": true` to your `tsconfig.json`?

**Comment by migueldv90** [comment]
I encountered this problem when updating Angular 17 to 18.2.8.

"skipLibCheck": true to your tsconfig.json - worked

also 

npm install --save-dev @rrweb/types rrweb-snapshot - worked

Are these the appropriate solutions or stopgaps?

**Comment by vvolodin** [comment]
I haven't tried "skipLibCheck" since I really don't want to have it on anyway. I'm sticking to the older version of posthog for now.

**Comment by pauldambra** [comment]
we have https://github.com/rrweb-io/rrweb/pull/1593 open with rrweb... we'd like to fix the root cause here and be able to import the types and not the packages so that our dependencies are clear

**Comment by siimveskilt** [comment]
Looks like it has been merged and released.

**Comment by marandaneto** [comment]
Public typings no longer require rrweb-snapshot
