### ISSUE TITLE
"TypeError: this.people.delete_user is undefined" when calling posthog.opt_out_capturing() 

### ISSUE THREAD

**Issue by brianjychan** [PostHog/posthog-js#39]
I'm loading PostHog via the npm module.

Then, in my React app's logic, when I run the following (awhile after init has already completed):

```
posthog.identify('testUser')
posthog.opt_out_capturing();
```

I get the error:
`TypeError: this.people.delete_user is not a function. (In 'this.people.delete_user()', 'this.people.delete_user' is undefined)`

I also tried switching the order of those two lines, which results in no errors thrown. However, in both cases autocapture events are still sent through.

I might be following an incorrect usage pattern. Am I missing something?

**Comment by mariusandra** [comment]
This was solved a while ago. The problem was IIRC with loading posthog via npm.

**Comment by JayGray** [comment]
@mariusandra any details on how or which commit solved this because I still face the error.
Version: 1.4.5
Module: npm

Error:
```js
module.js:5371 Uncaught TypeError: this.people.delete_user is not a function
    at PostHogLib.push.OKHC.PostHogLib.opt_out_capturing (module.js:5371)
    at <anonymous>:1:16
```

Thx

**Comment by macobo** [comment]
Sorry for the late note - fix has landed, will be patched in the upcoming released.
