### ISSUE TITLE
Cannot find module 'rrweb/src/types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by florianherrengt** [PostHog/posthog-js#437]
I think it should be part of the dependencies instead of dev dependencies. 

https://github.com/PostHog/posthog-js/blob/master/package.json#L66

**Comment by pauldambra** [comment]
sorry we missed this!
i'm going to assume this was fixed already or more people would have reported it 🙈

**Comment by kyleatpanoptyc** [comment]
@pauldambra it wasn't fixed: https://github.com/PostHog/posthog-js/blob/main/package.json#L61-L63

Would you accept a PR that moves these dependencies?

**Comment by nikolaihe** [comment]
Is there a solution for this yet? I am still getting this error.

**Comment by da201501245** [comment]
I am also getting this error please help!!
